### ISSUE TITLE
Mac systems have error with  npm start 

### ISSUE THREAD

**Issue by doudouma** [BuilderIO/gpt-crawler#87]
> @builder.io/gpt-crawler@1.0.0 start
> npm run start:dev

> @builder.io/gpt-crawler@1.0.0 start:dev
> cross-env NODE_ENV=development npm run build && node dist/src/main.js

> @builder.io/gpt-crawler@1.0.0 build
> tsc

src/core.ts:56:30 - error TS2339: Property 'request' does not exist on type 'PlaywrightCrawlingContext<Dictionary>'.

56       async requestHandler({ request, page, enqueueLinks, log, pushData }) {
                                ~~~~~~~

src/core.ts:56:45 - error TS2339: Property 'enqueueLinks' does not exist on type 'PlaywrightCrawlingContext<Dictionary>'.

56       async requestHandler({ request, page, enqueueLinks, log, pushData }) {
                                               ~~~~~~~~~~~~

src/core.ts:56:59 - error TS2339: Property 'log' does not exist on type 'PlaywrightCrawlingContext<Dictionary>'.

56       async requestHandler({ request, page, enqueueLinks, log, pushData }) {
                                                             ~~~

src/core.ts:56:64 - error TS2339: Property 'pushData' does not exist on type 'PlaywrightCrawlingContext<Dictionary>'.

56       async requestHandler({ request, page, enqueueLinks, log, pushData }) {
                                                                  ~~~~~~~~

src/core.ts:110:24 - error TS2339: Property 'log' does not exist on type 'PlaywrightCrawlingContext<Dictionary>'.

110         async ({ page, log }) => {
                           ~~~


Found 5 errors in the same file, starting at: src/core.ts:56

**Comment by marcelovicentegc** [comment]
This issue might be related to https://github.com/BuilderIO/gpt-crawler/issues/83.

@doudouma, what node version are you using?

**Comment by guillermoscript** [comment]
I'm using node 20.9.0 and v18.12.1 with my M1 mac, and its working are you using a lower version @doudouma ?

**Comment by louisdtb** [comment]
Confirming everything works on my mac m1 with node v16.17.1. Have you tried deleting node_modules and rerunning `npm i`?
